######################################
#       SimpleBanHammer 1.0.9v       #
#             By _Monkeee            #
######################################

# DO NOT TOUCH UNDER ANY CIRCUMSTANCES!
# current-version: "1.0.4"

# Type: Bool. Weather the ban is broadcasted to all the players.
enable-broadcast: false

# Type: str. Message that is broadcasted to all the players.
# ONLY IF 'enable-broadcast' IS ENABLED
# Vars:
broadcast-message: '&cPlayer %prefix_player% &chas been banned by %prefix_admin% with the reason: &e%reason%'

# Type: str, The ban command used to ban players. (ex. tempban, ban, eban, mute, ...)
# REQUIRED: The moderator has to have permission to use said command!
ban-command: 'ban %player% %reason%'

# Type: str, The ban message if non arguments given.
default-reason: "The Ban Hammer Has Spoken!"

# Type: Bool, If op players should receive Update Notifications when joining.
update-notifier: true

# Type: Str, The item for the ban hammer. NOTE: HAS TO BE A VALID ITEM FORMAT (ex.: mace, iron_axe, diamond_axe,...)
item-banhammer: "iron_axe"

# Type: Str, Link of a discord webhook for the ban logs
webhook-link: ""