
# DO NOT TOUCH UNDER ANY CIRCUMSTANCES!
# current-version: "1.0.4"

# Type: Bool. Weather the ban is broadcasted to all the players.
enable-broadcast: false

# Type: str. Message that is broadcasted to all the players.
# ONLY IF 'enable-broadcast' IS ENABLED
# Vars:
broadcast-message: '&cPlayer %prefix_player% &chas been banned by %prefix_admin% with the reason: &e%reason%'

# Type: str, The ban command used to ban players. (ex. tempban, ban, eban, mute, ...)
# REQUIRED: The moderator has to have permission to use said command!
ban-command: 'ban %player% %reason%'

# Type: str, The ban message if non arguments given.
default-reason: "The Ban Hammer Has Spoken!"

# Type: Bool, If op players should receive Update Notifications when joining.
update-notifier: true

# Type: Str, The item for the ban hammer. NOTE: HAS TO BE A VALID ITEM FORMAT (ex.: mace, iron_axe, diamond_axe,...)
item-banhammer: "IRON_AXE"

# Type: List, The reasons, admins will be recommended to.
reasons:
  - Cheating
  - Exploiting
  - Abusing
  - Harassment

# Type: Str, If the executed command is run by the player or the console.
enable-console-sender: true

# Type: Str, Discord webhook url for logging bans to discord.
# LEAVE EMPTY IF NOT USED
discord-webhook: ""